name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PAT }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag coffeexdev/sales-listener:$(date +%s)
      
    - name: Push the docker image
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: docker push coffeexdev/sales-listener:$(date +%s) && docker push coffeexdev/sales-listener:latest
